import{i,S as f}from"./assets/vendor-0fc460d7.js";(function(){const n=document.createElement("link").relList;if(n&&n.supports&&n.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const a of r.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&s(a)}).observe(document,{childList:!0,subtree:!0});function o(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function s(e){if(e.ep)return;e.ep=!0;const r=o(e);fetch(e.href,r)}})();const d="https://pixabay.com/api/";function m(t){return fetch(`${d}?key=44783879-183c1ceb2e13ce0ff75e5d5ac&q=${t}&image_type=photo&orientation=horizontal&safesearch=true`).then(o=>{if(!o.ok)throw new Error(o.status);return o.json()})}const l=document.querySelector(".gallery");function y(t){const n=t.map(({webformatURL:o,largeImageURL:s,tags:e,likes:r,views:a,comments:c,downloads:u})=>`<div class="gallery-images">
                        <a href="${s}">
                            <img class="gallery-img" src="${o}" alt="${e}" loading="lazy" />
                        </a>
                        <div class="info-image">
                            <p class="info-item">Likes: <span class="info-value">${r}</span></p>
                            <p class="info-item">Views: <span class="info-value">${a}</span></p>
                            <p class="info-item">Comments: <span class="info-value">${c}</span></p>
                            <p class="info-item">Downloads: <span class="info-value">${u}</span></p>
                        </div>
                    </div>`).join("");l.insertAdjacentHTML("beforeend",n)}function p(){l.innerHTML=""}document.querySelector(".search-form");document.querySelector(".gallery");document.addEventListener("DOMContentLoaded",()=>{const t=document.getElementById("searchForm");t?t.addEventListener("submit",g):console.error("Form not found")});function g(t){t.preventDefault();const n=t.currentTarget,o=n.elements.query.value.trim().toLowerCase();if(!o){i.error({title:"Error",message:"Please enter a search query."});return}p(),h(),m(o).then(s=>{const e=s.hits;e.length===0?i.info({title:"Info",message:"Sorry, there are no images matching your search query. Please try again!"}):(y(e),new f(".gallery a").refresh())}).catch(s=>{console.error("Error fetching data:",s),i.error({title:"Error",message:"An error occurred while fetching data. Please try again later."})}).finally(()=>{L(),n.reset()})}function h(){document.getElementById("loader").style.display="block"}function L(){document.getElementById("loader").style.display="none"}
//# sourceMappingURL=commonHelpers.js.map
